version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  #  mongo-seed:
  #    build:
  #      context: .
  #      dockerfile: db.dockerfile
  #      args:
  #        input: out
  #    depends_on:
  #      - mongo

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
