name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore Gradle cache
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Build Apps
        run: ./gradlew assemble
      - name: Cache Gradle
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Upload Static Web App Artifact
        uses: actions/upload-artifact@v2
        id: upload
        with:
          path: app/client/build/distributions
          name: static-web-app
          if-no-files-found: error
      - name: Build App Docker image & push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: app
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: mpetuska/kamp/app
          tag_with_sha: true
          add_git_labels: true
      - name: Build Scanner Docker image & push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: app
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: mpetuska/kamp/scanner
          tag_with_sha: true
          add_git_labels: true

  deploy-StaticWebApp:
    runs-on: ubuntu-latest
    name: Deploy Static Web App
    needs: [ "build" ]
    steps:
      - name: Download Static Web App Artifact
        uses: actions/download-artifact@v2
        with:
          name: static-web-app
      - name: Prepare Env
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: app/client/build/distributions/application.env
          contents: |
            API_URL=https://kamp.azurewebsites.net
          write-mode: overwrite
      - name: Deploy Azure Static Web App
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AMBITIOUS_WATER_0BC116E03 }}
          repo_token: ${{ github.token }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/app/client/build/distributions"
          ###### End of Repository/Build Configurations ######
