name: Scan

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: INFO
  schedule:
    - cron: '0 0 * * *'

env:
  API_URL: https://kamp.azurewebsites.net
  ADMIN_USER: ${{ secrets.API_ADMIN_USER }}
  ADMIN_PASSWORD: ${{ secrets.API_ADMIN_PASSWORD }}
  IMAGE: docker.pkg.github.com/mpetuska/kamp/scanner:latest
  LOG_LEVEL: ${{ github.event.inputs.logLevel }}

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        range:
          - from: c
            to: c
          - from: o
            to: p
          - from: a
            to: b
          - from: d
            to: f
          - from: g
            to: l
          - from: m
            to: n
          - from: q
            to: r
          - from: s
            to: z
    steps:
      - uses: docker/login-action@v1.8.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: docker run -a stderr -a stdout -e "LOG_LEVEL=${LOG_LEVEL:-INFO}" -e API_URL -e ADMIN_USER -e ADMIN_PASSWORD ${{ env.IMAGE }} mavenCentral --from ${{ matrix.range.from }} --to ${{ matrix.range.to }}
