name: Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

env:
  API_URL: https://kamp.azurewebsites.net
  ADMIN_USER: ${{ secrets.API_ADMIN_USER }}
  ADMIN_PASSWORD: ${{ secrets.API_ADMIN_PASSWORD }}
  IMAGE: docker.pkg.github.com/mpetuska/kamp/scanner:latest
  LOG_LEVEL: DEBUG

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        from: [ 'a', 'g', 'm', 's', 'y' ]
        to: [ 'f', 'l', 'r', 'x', 'z' ]
    steps:
      - uses: docker/login-action@v1.8.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: docker run -a stderr -a stdin -e LOG_LEVEL -e API_URL -e ADMIN_USER -e ADMIN_PASSWORD ${{ env.IMAGE }} mavenCentral --from ${{ matrix.from }} --to ${{ matrix.to }}
