name: Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

env:
  API_URL: https://kamp.azurewebsites.net
  ADMIN_USER: ${{ secrets.API_ADMIN_USER }}
  ADMIN_PASSWORD: ${{ secrets.API_ADMIN_PASSWORD }}
  IMAGE: docker.pkg.github.com/mpetuska/kamp/scanner:latest
  LOG_LEVEL: DEBUG

jobs:
  scan-a-f:
    runs-on: ubuntu-latest
    name: Scan a..f
    env:
      FROM: a
      TO: f
    steps:
      - uses: docker/login-action@v1.8.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: docker run -e LOG_LEVEL -e API_URL -e ADMIN_USER -e ADMIN_PASSWORD ${{ env.IMAGE }} mavenCentral --from $FROM --to $TO

  scan-g-l:
    runs-on: ubuntu-latest
    name: Scan g..l
    env:
      FROM: g
      TO: l
    steps:
      - uses: docker/login-action@v1.8.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: docker run -e LOG_LEVEL -e API_URL -e ADMIN_USER -e ADMIN_PASSWORD ${{ env.IMAGE }} mavenCentral --from $FROM --to $TO

  scan-m-r:
    runs-on: ubuntu-latest
    name: Scan m..r
    env:
      FROM: m
      TO: r
    steps:
      - uses: docker/login-action@v1.8.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: docker run -e LOG_LEVEL -e API_URL -e ADMIN_USER -e ADMIN_PASSWORD ${{ env.IMAGE }} mavenCentral --from $FROM --to $TO

  scan-s-z:
    runs-on: ubuntu-latest
    name: Scan s..z
    env:
      FROM: s
      TO: z
    steps:
      - uses: docker/login-action@v1.8.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - run: docker run -e LOG_LEVEL -e API_URL -e ADMIN_USER -e ADMIN_PASSWORD ${{ env.IMAGE }} mavenCentral --from $FROM --to $TO
